/**
 * Import Android system libraries as shown below:
 * import { Context } from "android.content.Context";
 * Optional; import only when needed.
 */

/* Import variables defined in interface.uts. */
import { MyApiOptions, MyApiResult, MyApi, MyApiSync } from '../interface.uts';

/* Import variables defined in unierror.uts. */
import { MyApiFailImpl } from '../unierror';

/**
 * Importing third-party libraries.
 * Optional; import only when needed.
 *
 * Android supports two methods for adding third-party libraries:
 * 1. Recommended: add the library repository coordinates to the dependencies field in config.json. See the [dependency documentation](https://uniapp.dcloud.net.cn/plugin/uts-plugin.html#dependencies).
 * 2. Add an AAR or JAR directly to the libs directory. See the [Android native configuration documentation](https://uniapp.dcloud.net.cn/plugin/uts-plugin.html#android%E5%B9%B3%E5%8F%B0%E5%8E%9F%E7%94%9F%E9%85%8D%E7%BD%AE).
 *
 * After adding the library with either method, import its types where they are used:
 * import { LottieAnimationView } from 'com.airbnb.lottie.LottieAnimationView'
 */

/**
 * UTSAndroid is a built-in platform object and can be used without an import. See the [UTSAndroid documentation](https://uniapp.dcloud.net.cn/uts/utsandroid.html#utsandroid).
 */

/**
 * Asynchronous method.
 *
 * Usage in a uni-app project (Vue/NVue):
 * 1. Import the method: import { myApi } from "@/uni_modules/uts-api"
 * 2. Call the method:
 * myApi({
 *   paramA: false,
 *   complete: (res) => {
 *      console.log(res)
 *   }
 * });
 *
 * Usage in a uni-app x project (UVue):
 * 1. Import the method and parameter type: import { myApi, MyApiOptions } from "@/uni_modules/uts-api";
 * 2. Call the method:
 * let options = {
 *   paramA: false,
 *   complete: (res : any) => {
 *     console.log(res)
 *   }
 * } as MyApiOptions;
 * myApi(options);
 */
export const myApi : MyApi = function (options : MyApiOptions) {
  if (options.paramA == true) {
    // Return data.
    const res : MyApiResult = {
      fieldA: 85,
      fieldB: true,
      fieldC: 'some message'
    };
    options.success?.(res);
    options.complete?.(res);
  } else {
    // Return an error.
    const err = new MyApiFailImpl(9010001);
    options.fail?.(err)
    options.complete?.(err)
  }
}

/**
 * Synchronous method.
 *
 * Usage in a uni-app project (Vue/NVue):
 * 1. Import the method: import { myApiSync } from "@/uni_modules/uts-api"
 * 2. Call the method: myApiSync(true)
 *
 * Usage in a uni-app x project (UVue):
 * 1. Import the method and parameter type: import { myApiSync } from "@/uni_modules/uts-api";
 * 2. Call the method: myApiSync(true)
 */
export const myApiSync : MyApiSync = function (paramA : boolean) : MyApiResult {
  // Return the actual value produced by the plugin.
  const res : MyApiResult = {
    fieldA: 85,
    fieldB: paramA,
    fieldC: 'some message'
  };
  return res;
}

/**
 * For more plugin development information, see https://uniapp.dcloud.net.cn/plugin/uts-plugin.html.
 */
