apply plugin: 'com.android.library'

def sdkVersion = getDefaultProperties().getProperty("SDK_VERSION", "0.0.0")

android {
    namespace "com.ft.sdk.uniapp"
    compileSdkVersion 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 2
        versionName "${sdkVersion}"

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

        buildConfigField("String", "FT_UNI_APP_SDK_VERSION", "\"${sdkVersion}\"")

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    libraryVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "gc-uniplugin-${defaultConfig.versionName}.aar"
        }
    }

}

dependencies {
    compileOnly fileTree(dir: '../UniMPSDK/libs', include: ['uniapp-v8-release.aar'])

    compileOnly 'androidx.recyclerview:recyclerview:1.0.0'
    compileOnly 'androidx.legacy:legacy-support-v4:1.0.0'
    compileOnly 'androidx.appcompat:appcompat:1.0.0'
    implementation 'com.alibaba:fastjson:1.1.46.android'
    implementation 'com.cloudcare.ft.mobile.sdk.tracker.agent:ft-sdk:1.7.5'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.cloudcare.ft.mobile.sdk.tracker.agent:ft-native:1.1.3'

    /*implementation 'com.android.support:appcompat-v7:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'*/
}
