buildscript {
    ext {
        getDefaultProperties = this.&getDefaultProperties
    }

    repositories {
        google()
        mavenCentral()
        maven { url 'https://mvnrepo.guance.com/repository/maven-releases' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath 'com.cloudcare.ft.mobile.sdk.tracker.plugin:ft-plugin:1.3.8'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://mvnrepo.guance.com/repository/maven-releases' }
    }
}

def getDefaultProperties() {
    Properties properties = new Properties()
    File versionFile = new File(rootProject.projectDir, '../../../.version')
    if (versionFile.exists()) {
        versionFile.withInputStream { properties.load(it) }
    }
    return properties
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
