const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const versionFilePath = path.join(root, '.version');
const changelogPath = path.join(root, 'CHANGELOG.md');
const SEMVER_PATTERN = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/;

// .version is the canonical release version. Every entry here is derived
// release metadata or checked-in generated source that is shipped by CI.
const versionTargets = [
    {
        path: 'Hbuilder_Example/uni_modules/GC-JSPlugin/package.json',
        pattern: /("version"\s*:\s*")([^"]+)(")/
    },
    {
        path: 'Hbuilder_Example/uni_modules/GC-UniPlugin/package.json',
        pattern: /("version"\s*:\s*")([^"]+)(")/
    },
    {
        path: 'Hbuilder_Example/uni_modules/GC-UniSessionReplay/package.json',
        pattern: /("version"\s*:\s*")([^"]+)(")/
    },
    {
        path: 'Hbuilder_Example/uni_modules/GC-UniPlugin/utssdk/bridge.uts',
        pattern: /(export const GC_UTS_BRIDGE_VERSION: string = ['"])([^'"]+)(['"])/
    },
    {
        path: 'native-projects/native-sdk-hybrid/android/unimoduleGCUniPlugin/src/main/kotlin/index.kt',
        pattern: /(val GC_UTS_BRIDGE_VERSION: String = ")([^"]+)(")/
    },
    {
        path: 'native-projects/native-sdk-hybrid/ios/HBuilder-uniPluginDemo/UTSFrameworks/unimoduleGCUniPlugin/Sources/index.swift',
        pattern: /(public var GC_UTS_BRIDGE_VERSION: String = ")([^"]+)(")/
    },
    {
        path: 'native-projects/unimp-host-extension/ios/GCUniPlugin/GC-UniPlugin-App.xcodeproj/project.pbxproj',
        pattern: /(MARKETING_VERSION = )([^;]+)(;)/,
        expectedMatches: 2
    },
    {
        path: 'native-projects/unimp-host-extension/ios/GCUniPlugin/GC-UniPlugin-App/Classes/GC-UniPlugin-App-Version.h',
        pattern: /(#define UniPluginAppVersion @")([^"]+)(")/
    },
    {
        path: 'native-projects/unimp-host-extension/ios/GCUniPlugin/GC-UniPlugin-App.podspec',
        pattern: /(s\.version\s*=\s*')([^']+)(')/
    },
    // The Harmony native-host example is generated by HBuilderX and may be
    // intentionally absent. When checked in, keep all of its release metadata
    // synchronized with the canonical version as well.
    {
        path: 'native-projects/native-sdk-hybrid/harmony/HBuilder-uniPluginDemo/uni_modules/GC-UniPlugin/oh-package.json5',
        pattern: /("version"\s*:\s*")([^"]+)(")/,
        optional: true
    },
    {
        path: 'native-projects/native-sdk-hybrid/harmony/HBuilder-uniPluginDemo/uni_modules/GC-UniPlugin/BuildProfile.ets',
        pattern: /(HAR_VERSION\s*=\s*')([^']+)(')/,
        optional: true
    },
    {
        path: 'native-projects/native-sdk-hybrid/harmony/HBuilder-uniPluginDemo/uni_modules/GC-UniPlugin/utssdk/app-harmony/index.ets',
        pattern: /(const GC_UTS_BRIDGE_VERSION: string = ')([^']+)(')/,
        optional: true
    }
];

function normalizeVersion(value) {
    return String(value || '').trim().replace(/^refs\/tags\//, '');
}

function assertValidVersion(version) {
    if (!SEMVER_PATTERN.test(version)) {
        throw new Error(`Invalid semantic version: ${version || '<empty>'}`);
    }
}

function readCanonicalVersion() {
    if (!fs.existsSync(versionFilePath)) {
        throw new Error(`Version file not found: ${versionFilePath}`);
    }
    const source = fs.readFileSync(versionFilePath, 'utf8');
    const match = /^SDK_VERSION=([^\r\n]+)\r?\n?$/.exec(source);
    if (!match) {
        throw new Error('.version must contain exactly SDK_VERSION=<semantic-version>');
    }
    const version = normalizeVersion(match[1]);
    assertValidVersion(version);
    return version;
}

function findVersionMatches(target, source) {
    const flags = target.pattern.flags.includes('g')
        ? target.pattern.flags
        : `${target.pattern.flags}g`;
    const matches = Array.from(source.matchAll(new RegExp(target.pattern.source, flags)));
    const expectedMatches = target.expectedMatches || 1;
    if (matches.length !== expectedMatches) {
        throw new Error(
            `${target.path} must contain exactly ${expectedMatches} supported version marker(s); found ${matches.length}`
        );
    }
    return matches;
}

function inspectTargets() {
    const inspected = [];
    for (const target of versionTargets) {
        const absolutePath = path.join(root, target.path);
        if (!fs.existsSync(absolutePath)) {
            if (target.optional) {
                continue;
            }
            throw new Error(`Required version target not found: ${target.path}`);
        }
        const source = fs.readFileSync(absolutePath, 'utf8');
        const matches = findVersionMatches(target, source);
        inspected.push({
            ...target,
            absolutePath,
            source,
            matches,
            versions: matches.map(match => match[2])
        });
    }
    return inspected;
}

function assertChangelogVersion(version) {
    if (!fs.existsSync(changelogPath)) {
        throw new Error('CHANGELOG.md not found');
    }
    const changelog = fs.readFileSync(changelogPath, 'utf8');
    const firstHeading = /^#\s+([^\r\n]+)$/m.exec(changelog);
    if (!firstHeading || firstHeading[1].trim() !== version) {
        throw new Error(
            `CHANGELOG.md must start with release ${version}; found ${firstHeading ? firstHeading[1].trim() : '<none>'}`
        );
    }
}

function checkVersionConsistency(expectedVersion) {
    const version = readCanonicalVersion();
    const expected = expectedVersion ? normalizeVersion(expectedVersion) : version;
    assertValidVersion(expected);
    if (version !== expected) {
        throw new Error(`Expected version ${expected}, but .version contains ${version}`);
    }

    const mismatches = inspectTargets().flatMap(target => target.versions
        .filter(targetVersion => targetVersion !== version)
        .map(targetVersion => `${target.path}: ${targetVersion}`));
    if (mismatches.length > 0) {
        throw new Error(
            `Release version ${version} is inconsistent:\n${mismatches.map(item => `- ${item}`).join('\n')}`
        );
    }
    if (expectedVersion) {
        assertChangelogVersion(version);
    }
    return version;
}

function updateVersion(requestedVersion) {
    const version = requestedVersion
        ? normalizeVersion(requestedVersion)
        : readCanonicalVersion();
    assertValidVersion(version);
    if (requestedVersion) {
        assertChangelogVersion(version);
    }

    // Inspect every target before writing anything so a missing/generated
    // marker cannot leave the repository partially updated.
    const inspected = inspectTargets();
    const writes = inspected.map(target => {
        const { matches, source } = target;
        let cursor = 0;
        let content = '';
        for (const match of matches) {
            content += source.slice(cursor, match.index);
            content += `${match[1]}${version}${match[3]}`;
            cursor = match.index + match[0].length;
        }
        content += source.slice(cursor);
        return { ...target, content };
    });

    fs.writeFileSync(versionFilePath, `SDK_VERSION=${version}\n`, 'utf8');
    for (const target of writes) {
        fs.writeFileSync(target.absolutePath, target.content, 'utf8');
        console.log(`Updated ${target.path} to ${version}`);
    }

    checkVersionConsistency(requestedVersion ? version : undefined);
    console.log(`Release version is consistent: ${version}`);
    return version;
}

function main(argv) {
    if (argv[0] === '--check') {
        const version = checkVersionConsistency(argv[1]);
        console.log(`Release version is consistent: ${version}`);
        return;
    }
    if (argv.length > 1) {
        throw new Error('Usage: node scripts/update-version.js [version] | --check [expected-version]');
    }
    updateVersion(argv[0]);
}

if (require.main === module) {
    try {
        main(process.argv.slice(2));
    } catch (error) {
        console.error(`Failed to update version: ${error.message}`);
        process.exit(1);
    }
}

module.exports = {
    SEMVER_PATTERN,
    assertValidVersion,
    checkVersionConsistency,
    normalizeVersion,
    readCanonicalVersion,
    updateVersion,
    versionTargets
};
