import {
	GCSessionReplayConfig
} from './interface.uts'

export class GCUniSessionReplay {
	static setConfig(config: GCSessionReplayConfig) {}
}

export class GCSessionReplayTouchPrivacy {
	static readonly SHOW: string = 'show'
	static readonly HIDE: string = 'hide'
}

export class GCSessionReplayTextAndInputPrivacy {
	static readonly MASK_SENSITIVE_INPUTS: string = 'maskSensitiveInputs'
	static readonly MASK_ALL_INPUTS: string = 'maskAllInputs'
	static readonly MASK_ALL: string = 'maskAll'
}

export class GCSessionReplayImagePrivacy {
	static readonly MASK_NON_BUNDLED_ONLY: string = 'maskNonBundledOnly'
	static readonly MASK_ALL: string = 'maskAll'
	static readonly MASK_NONE: string = 'maskNone'
}
