/**
 * Import iOS system libraries as shown below:
 * import { UIDevice } from "UIKit";
 * Optional; import only when needed.
 */

/* Import variables defined in interface.uts. */
import { MyApiOptions, MyApiResult, MyApi, MyApiSync } from '../interface.uts';

/* Import variables defined in unierror.uts. */
import { MyApiFailImpl } from '../unierror';

/**
 * Importing third-party libraries.
 * Optional; import only when needed.
 *
 * iOS supports two methods for adding third-party libraries:
 * 1. For frameworks or static libraries, place `.framework` files in `./Frameworks` and `.a` files in `./Libs`. See the [iOS native configuration documentation](https://uniapp.dcloud.net.cn/plugin/uts-plugin.html#ios-%E5%B9%B3%E5%8F%B0%E5%8E%9F%E7%94%9F%E9%85%8D%E7%BD%AE).
 * 2. For CocoaPods, add the pod information to the dependencies-pods field in config.json. See the [CocoaPods documentation](https://uniapp.dcloud.net.cn/plugin/uts-ios-cocoapods.html).
 *
 * After adding a third-party library, import its types where they are used:
 * import { LottieLoopMode } from 'Lottie'
 */

/**
 * UTSiOS is a built-in platform object and can be used without an import. See the [UTSiOS documentation](https://uniapp.dcloud.net.cn/uts/utsios.html).
 */

/**
 * Asynchronous method.
 *
 * Usage in a uni-app project (Vue/NVue):
 * 1. Import the method: import { myApi } from "@/uni_modules/uts-api"
 * 2. Call the method:
 * myApi({
 *   paramA: false,
 *   complete: (res) => {
 *      console.log(res)
 *   }
 * });
 */
export const myApi : MyApi = function (options : MyApiOptions) {

  if (options.paramA == true) {
    // Return data.
    const res : MyApiResult = {
      fieldA: 85,
      fieldB: true,
      fieldC: 'some message'
    };
    options.success?.(res);
    options.complete?.(res);

  } else {
    // Return an error.
    let failResult = new MyApiFailImpl(9010001);
    options.fail?.(failResult)
    options.complete?.(failResult)
  }

}

/**
 * Synchronous method.
 *
 * Usage in a uni-app project (Vue/NVue):
 * 1. Import the method: import { myApiSync } from "@/uni_modules/uts-api"
 * 2. Call the method: myApiSync(true)
 */
export const myApiSync : MyApiSync = function (paramA : boolean) : MyApiResult {
  // Return the actual value produced by the plugin.
  const res : MyApiResult = {
    fieldA: 85,
    fieldB: paramA,
    fieldC: 'some message'
  };
  return res;
}

/**
 * For more plugin development information, see https://uniapp.dcloud.net.cn/plugin/uts-plugin.html.
 */
